// Self-contained dashboard assets served by the mock file-serving layer.
// The dashboard HTML is fully inline (no external scripts/links) so it renders
// inside an iframe via `srcdoc` with no network dependency.

export const DASHBOARD_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Q2 Revenue Dashboard</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #f7f8fa; color: #1a2233; padding: 24px; }
  .head { display: flex; align-items: baseline; justify-content: space-between; margin-bottom: 20px; }
  .head h1 { font-size: 20px; font-weight: 700; }
  .head .sub { font-size: 12px; color: #6b7280; }
  .kpis { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 18px; }
  .kpi { background: #fff; border: 1px solid #eceef1; border-radius: 12px; padding: 16px; }
  .kpi .label { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #8b93a1; margin-bottom: 8px; }
  .kpi .val { font-size: 24px; font-weight: 700; }
  .kpi .delta { font-size: 12px; font-weight: 600; margin-top: 4px; }
  .delta.up { color: #16a34a; } .delta.down { color: #dc2626; }
  .grid { display: grid; grid-template-columns: 1.4fr 1fr; gap: 14px; }
  .card { background: #fff; border: 1px solid #eceef1; border-radius: 12px; padding: 18px; }
  .card h3 { font-size: 13px; font-weight: 700; margin-bottom: 14px; }
  .bars { display: flex; align-items: flex-end; gap: 14px; height: 180px; padding-top: 10px; }
  .bar { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 6px; height: 100%; justify-content: flex-end; }
  .bar .col { width: 100%; max-width: 46px; background: linear-gradient(180deg, #6366f1, #818cf8); border-radius: 6px 6px 0 0; }
  .bar .m { font-size: 10px; color: #6b7280; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; color: #8b93a1; font-weight: 600; padding: 8px 6px; border-bottom: 1px solid #eceef1; text-transform: uppercase; font-size: 10px; letter-spacing: .03em; }
  td { padding: 9px 6px; border-bottom: 1px solid #f1f2f4; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .pill { font-size: 10px; padding: 2px 7px; border-radius: 999px; font-weight: 600; }
  .pill.win { background: #dcfce7; color: #166534; } .pill.risk { background: #fef3c7; color: #92400e; }
</style>
</head>
<body>
  <div id="root">
    <div class="head">
      <div>
        <h1>Q2 Revenue Dashboard</h1>
        <div class="sub">Fiscal Q2 2026 · refreshed automatically on data sync</div>
      </div>
      <div class="sub">Generated by Analytics Agent</div>
    </div>

    <div class="kpis">
      <div class="kpi"><div class="label">Total Revenue</div><div class="val">$4.82M</div><div class="delta up">▲ 14.2% QoQ</div></div>
      <div class="kpi"><div class="label">New ARR</div><div class="val">$1.13M</div><div class="delta up">▲ 9.6% QoQ</div></div>
      <div class="kpi"><div class="label">Win Rate</div><div class="val">27.4%</div><div class="delta down">▼ 1.8 pts</div></div>
      <div class="kpi"><div class="label">Avg Deal Size</div><div class="val">$38.6K</div><div class="delta up">▲ 5.1% QoQ</div></div>
    </div>

    <div class="grid">
      <div class="card">
        <h3>Revenue by Month</h3>
        <div class="bars">
          <div class="bar"><div class="col" style="height:58%"></div><div class="m">Apr</div></div>
          <div class="bar"><div class="col" style="height:72%"></div><div class="m">May</div></div>
          <div class="bar"><div class="col" style="height:91%"></div><div class="m">Jun</div></div>
          <div class="bar"><div class="col" style="height:64%"></div><div class="m">Jul</div></div>
          <div class="bar"><div class="col" style="height:80%"></div><div class="m">Aug</div></div>
          <div class="bar"><div class="col" style="height:100%"></div><div class="m">Sep</div></div>
        </div>
      </div>
      <div class="card">
        <h3>Top Accounts</h3>
        <table>
          <thead><tr><th>Account</th><th class="num">ARR</th><th>Status</th></tr></thead>
          <tbody>
            <tr><td>Northwind Traders</td><td class="num">$412K</td><td><span class="pill win">Expanding</span></td></tr>
            <tr><td>Contoso Ltd</td><td class="num">$388K</td><td><span class="pill win">Expanding</span></td></tr>
            <tr><td>Globex Corp</td><td class="num">$301K</td><td><span class="pill risk">At risk</span></td></tr>
            <tr><td>Initech</td><td class="num">$276K</td><td><span class="pill win">Stable</span></td></tr>
            <tr><td>Umbrella Inc</td><td class="num">$198K</td><td><span class="pill risk">At risk</span></td></tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- runtime hook for React-dashboard detection: ./runtime/app.js -->
</body>
</html>`;

export const DASHBOARD_MANIFEST = {
  version: "2.0",
  title: "Q2 Revenue Dashboard",
  created_at: "2026-06-01T10:00:00Z",
  widgets: {
    scoreboard: { id: "scoreboard", file: "widgets/scoreboard.jsx", name: "Scoreboard", data_source: "data/kpis.json", verified: false, verified_at: null },
    revenue_trend: { id: "revenue_trend", file: "widgets/revenue_trend.jsx", name: "Revenue by Month", data_source: "data/revenue_by_month.csv", verified: false, verified_at: null },
    top_accounts: { id: "top_accounts", file: "widgets/top_accounts.jsx", name: "Top Accounts", data_source: "data/top_accounts.csv", verified: false, verified_at: null },
  },
};

// Extra workspace files the viewers/tree may request.
export const DASHBOARD_FILES = {
  "output/dashboard/revenue_dashboard.html": { content: DASHBOARD_HTML, contentType: "text/html" },
  "output/dashboard/manifest.json": { content: JSON.stringify(DASHBOARD_MANIFEST, null, 2), contentType: "application/json" },
  "output/dashboard/runtime/app.js": { content: "/* mock dashboard runtime */", contentType: "application/javascript" },
  "output/dashboard/widgets/scoreboard.jsx": { content: "export default function Scoreboard({ data }) {\n  return <div className=\"scoreboard\">{/* KPI cards */}</div>\n}\n", contentType: "text/html" },
  "output/dashboard/widgets/revenue_trend.jsx": { content: "export default function RevenueTrend({ data }) {\n  return <div className=\"revenue-trend\">{/* bar chart */}</div>\n}\n", contentType: "text/html" },
  "output/dashboard/widgets/top_accounts.jsx": { content: "export default function TopAccounts({ data }) {\n  return <table>{/* top accounts */}</table>\n}\n", contentType: "text/html" },
  "data/kpis.json": { content: JSON.stringify({ total_revenue: 4820000, new_arr: 1130000, win_rate: 0.274, avg_deal: 38600 }, null, 2), contentType: "application/json" },
  "data/revenue_by_month.csv": { content: "month,revenue\nApr,612000\nMay,758000\nJun,961000\nJul,672000\nAug,840000\nSep,1052000\n", contentType: "text/csv" },
  "data/top_accounts.csv": { content: "account,arr,status\nNorthwind Traders,412000,Expanding\nContoso Ltd,388000,Expanding\nGlobex Corp,301000,At risk\nInitech,276000,Stable\nUmbrella Inc,198000,At risk\n", contentType: "text/csv" },
};
