export const OPTIMISTIC_SYNC_TIMEOUT_MS = 90_000;
export const OAUTH_POLL_INTERVAL_MS = 5000;
export const OAUTH_POPUP_CLOSE_CHECK_MS = 1000;
export const OAUTH_MAX_WAIT_MS = 5 * 60 * 1000;
export const OAUTH_FOCUS_COOLDOWN_MS = 3000;
export const SCHEMA_PENDING_POLL_INTERVAL_MS = 3000;
export const CREATING_MESSAGE_ROTATE_MS = 1800;
